/**
 * Auto-generated Payload CMS types stub.
 * This file is generated by `pnpm payload generate:types` when Payload is enabled.
 * For Town of Harmony (Builder.io-based), Payload collections are empty.
 */

export interface Config {
	collections: Record<string, never>;
	globals: Record<string, never>;
	db: {
		defaultIDType: "number";
	};
}

export interface User {
	id: number;
	email: string;
	createdAt: string;
	updatedAt: string;
}

export interface Faq {
	id: number;
	question: string;
	answer: unknown;
	category?: string;
	order?: number;
	createdAt: string;
	updatedAt: string;
}
